# Generated by Django 6.1.1 on 2026-09-12 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=150)),
                ('project_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('technologies', models.CharField(blank=True, max_length=500)),
                ('problem_statement', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('project_file', models.FileField(blank=True, null=True, upload_to='projects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement_score', models.FloatField(default=0)),
                ('innovation_score', models.FloatField(default=0)),
                ('technical_score', models.FloatField(default=0)),
                ('functionality_score', models.FloatField(default=0)),
                ('ui_ux_score', models.FloatField(default=0)),
                ('architecture_score', models.FloatField(default=0)),
                ('documentation_score', models.FloatField(default=0)),
                ('security_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='evaluator_app.project')),
            ],
        ),
    ]
